In [1]:
#installing NumPy libraries

In [2]:
!pip install numpy

In [3]:
#importing NumPy with alias

In [2]:
import numpy as np

In [5]:
#performing squaring operation on the elements of Python list and Numpy arrays to compare the syntax simplicity

In [6]:
#python list
A=[1,2,3,4,5]
A=[x**2 for x in A] #using list comprehension

In [7]:
A

[1, 4, 9, 16, 25]

In [8]:
#numPy arrays
A_np = np.array([1,2,3,4,5]) #creating an array using np.array

In [9]:
A_np

array([1, 2, 3, 4, 5])

In [10]:
A_np**2 #more simple syntax

array([ 1,  4,  9, 16, 25], dtype=int32)

In [ ]:
#demonstrating the space taken by the python list and numpy array

In [11]:
import sys as s

In [13]:
a=range(0,1000)
s.getsizeof(a)

48

In [14]:
#48 bytes is the size of the first block of the base element and its addresses memory location

In [15]:
n=np.arange(1000)

In [17]:
n.size #anlogous to len()

1000

In [18]:
#To have a function that is analogous to getsizeof()
n.itemsize

4

In [20]:
#only 4 Bytes of memory is taken for the first element

"""Numpy array here only takes 4000 (4bytes*1000 elements) bytes of memory but the python range take 48000 bytes"""

'Numpy array here only takes 4000 (4bytes*1000 elements) bytes of memory but the python range take 48000 bytes'

In [21]:
#demonstrating the processing speed of python list and numpy array

In [22]:
l=range(1000000)

In [23]:
%timeit [i**2 for i in l]

344 ms ± 41.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [24]:
n=np.arange(1000000)

In [25]:
%timeit n**2

2.1 ms ± 134 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
#the numpy array takes very less time (2.1 ms ± 134 µs) compared to the Python list (344 ms ± 41.8 ms)

## Other methods of numpy array

In [28]:
#.ndim - returns whether the array is 1D, 2D or 3D

In [29]:
#1D
arr1=np.array([1,2,3])
arr1.ndim

1

In [31]:
#2D
arr2=np.array([[1,2],[3,4]])
arr2.ndim

2

In [39]:
#3D
arr3 = np.array([[[1,2]],[[5,6]]])
arr3.ndim

3

In [40]:
#.shape - returns the number of elements in each dimension of the array

In [41]:
arr1.shape

(3,)

In [42]:
arr2.shape

(2, 2)

In [44]:
arr3.shape #has 2 elements at 1D level, 1 element at 2D level, 2 elements at 3D level

(2, 1, 2)

In [45]:
#np.arange() - very similar to range function np.arange(start, stop, step), starting element is included, stop element is not

In [47]:
np.arange(1,5,0.5) #step sizes can also be float

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

Linspace - used in machine learning often for equally spaced data

In [50]:
'''Between 0 to 10, 11 flags have to be placed, linspace returns the positions of those flags'''
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [51]:
np.linspace(0,36,6) 

array([ 0. ,  7.2, 14.4, 21.6, 28.8, 36. ])

In [52]:
"""10/10 gives the number of segments when 10 is divided by 10, but linspace finds the start and end point of those segments"""

'10/10 gives the number of segments when 10 is divided by 10, but linspace finds the start and end point of those segments'

Typecasting automatically and manually

In [57]:
#Automatic

In [62]:
"""When heterogenous data is given to the np array, the array converts the elements with the smaller memory into the type of element having the bigger memory - analogous to a small rat and big rat can use a bigger hole, but they both cannot use smaller hole"""

'When heterogenous data is given to the np array, the array converts the elements with the smaller memory into the type of element having the bigger memory - analogous to a small rat and big rat can use a bigger hole, but they both cannot use smaller hole'

In [59]:
np.array([1,2,3,4.0]) #here the int elements are converted to float, as float is bigger

array([1., 2., 3., 4.])

In [63]:
"""The order of priority of the data is Bool-->Integer-->Float-->String"""

'The order of priority of the data is Bool-->Integer-->Float-->String'

In [64]:
#Manual

In [68]:
np.array([1,2,3,4],dtype="f") #int to float

array([1., 2., 3., 4.], dtype=float32)

In [78]:
np.array([1.8,2,3,4],dtype="i") #float to int (int32 - integer of size 32)

array([1, 2, 3, 4], dtype=int32)

In [79]:
np.array([1,2,3,4],dtype="S") #int to string

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [80]:
np.array([0,1,2,"A",5.6],dtype="bool") #heterogenous to bool

array([False,  True,  True,  True,  True])

In [81]:
np.array([0,1,2,"A",5.6],dtype="i") #cannot convert string to int

ValueError: invalid literal for int() with base 10: 'A'

In [82]:
np.array([False,  True,  True,  True,  True],dtype="f") #bool to float

array([0., 1., 1., 1., 1.], dtype=float32)

In [83]:
np.array([0., 1., 1., 1., 1.],dtype="bool") #float to bool

array([False,  True,  True,  True,  True])

## Shape and dimensions of np arrays

In [85]:
m1=np.array([[1,2,3],
            [4,5,6]])

In [87]:
m1.shape #returns the number of (rows,columns,layers or aisles)

(2, 3)

In [89]:
m1.ndim #number of dimnesions

2

In [90]:
len(m1)

2

In [91]:
m2=np.array([[[1,2,3],
              [4,5,6]],[[1,2,3],
                        [4,5,6]]])

In [92]:
m2.shape

(2, 2, 3)

In [95]:
m2.ndim

3

In [96]:
len(m2)

2

## Converting 1D to multi dimensional array

In [97]:
#.reshape() - not a permanent change , should be assigned to a variable to store the change

In [104]:
m3=np.arange(0,12)

In [105]:
m3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [106]:
m3.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [107]:
m3.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
m3.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [130]:
#if any dimension is not known, just enter -1
m4=np.arange(14)

In [133]:
m4.reshape(2,-1) #by default it decides the other dimension, the number should be a multiple of total value

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

## Converting multi dimensional array back to 1 D array

In [ ]:
#flatten

In [128]:
m3.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Transpose

In [112]:
#1 D arrays cannot be transposed

In [113]:
a=np.arange(0,3)

In [114]:
a

array([0, 1, 2])

In [116]:
a.T #no change

array([0, 1, 2])

In [117]:
#reshape the 1 D arrays into 2 D

In [122]:
a=a.reshape(1,3)

In [125]:
a #notice the double square brackets after using the reshape function, 1 D array is converted to 2 D

array([[0, 1, 2]])

In [126]:
a.T

array([[0],
       [1],
       [2]])

## Zeros and ones function

In [137]:
np.zeros(3)

array([0., 0., 0.])

In [142]:
np.zeros((2,3)) #pass the dimensions as tuple

array([[0., 0., 0.],
       [0., 0., 0.]])

In [143]:
np.ones(3)

array([1., 1., 1.])

In [145]:
np.ones((2,3)) 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [146]:
np.ones((2,3))*5

array([[5., 5., 5.],
       [5., 5., 5.]])

## Diagonal

In [150]:
np.diag([1,2,3,4]) #takes the elements to be placed in the diagonal as input

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Identity

In [153]:
np.identity(3) #takes the number of rows

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Indexing

In [155]:
m5=np.arange(1,10).reshape(3,3)

In [156]:
m5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [158]:
#accessing element 6
m5[1][2]



6

In [159]:
m5[1,2] #also

6

In [162]:
m6=np.array([10,20,30,40,50,60])

In [164]:
#the multiple array elements can be accessed by the below method also
m6[[0,5,4]]

array([10, 60, 50])

## Slicing

In [166]:
m6[:2]

array([10, 20])

In [3]:
#Slicing a 2D array

A=np.array([[0,1,2], 
   [3,4,5],
   [6,7,8]])

In [4]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
'''To get the element in the Column index 1, that is [1,4,7]''',
A[:,1]
#Here, we need all the rows, hence the row part is just represented by ':', in the column part, the 1 column is mentioned

array([1, 4, 7])

In [13]:
'''To get the square matrix of size 2X2, [[1,2],[4,5]'''
A[0:2,1:]

array([[1, 2],
       [4, 5]])

In [9]:
A[:,1:]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
"""Note : In """

## Playing with Boolean

In [167]:
m5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [168]:
m5>6

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [169]:
m5[m5>6]

array([7, 8, 9])

In [170]:
m5[m5%2==0]

array([2, 4, 6, 8])

In [175]:
a=np.arange(1,4)
b=np.arange(4,7)

In [176]:
a

array([1, 2, 3])

In [177]:
b

array([4, 5, 6])

In [179]:
a+b #calls the universal function np.add()

array([5, 7, 9])

In [180]:
np.add(a,b)

array([5, 7, 9])

In [181]:
np.sum(a)

6